#%RAML 1.0 Trait

responses:
  400:
    description: 
        bad request

  401:
    description: 
        unauthrohrized
  404:
    description: 
          not found
  405:
    description: 
      methods not allowed
      
  500:
    description: 
          intrenal server error 
